# Generated by Django 4.0.6 on 2022-08-24 01:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import triplanit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('day', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_birth', models.DateField(blank=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('liked_plan', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('profile_img', models.ImageField(upload_to=triplanit.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='DayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('detailDescription', models.CharField(max_length=200)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('place_img', models.ImageField(default='', upload_to=triplanit.models.user_directory_path)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triplanit.planlist')),
            ],
        ),
    ]
