# Generated by Django 4.0.6 on 2022-08-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplanit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayevent',
            name='place_img',
        ),
    ]
