# Generated by Django 4.0.6 on 2022-08-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplanit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='id_token',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
