# Generated by Django 4.0.6 on 2022-08-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplanit', '0002_userlist_id_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='id_token',
        ),
    ]
