# Generated by Django 4.0.6 on 2022-08-24 01:59

from django.db import migrations, models
import triplanit.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplanit', '0002_remove_dayevent_place_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=triplanit.models.user_directory_path),
        ),
    ]
