# Generated by Django 4.0.6 on 2022-08-24 02:04

import django.contrib.postgres.fields
from django.db import migrations, models
import triplanit.models


class Migration(migrations.Migration):

    dependencies = [
        ('triplanit', '0003_alter_userlist_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='liked_plan',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=triplanit.models.user_directory_path),
        ),
    ]
