# Generated by Django 4.0.6 on 2022-08-24 02:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplanit', '0004_alter_userlist_date_birth_alter_userlist_liked_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='liked_plan',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), null=True, size=None),
        ),
    ]
